// Generated by scripts/generate-abis.mjs from packages/contracts/artifacts. Do not edit by hand.
// Regenerate after any contract change: npm run abis -w @hearth/web

export const HEARTH_VAULT_ABI = [
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "AlreadyFinalized",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "tier",
        "type": "uint8"
      }
    ],
    "name": "CarryNotPending",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "DrawAlreadyOpen",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "DrawNotAwarded",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "DrawNotOpen",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EnforcedPause",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "EvaluationWindowClosed",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "EvaluationWindowOpen",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ExpectedPause",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "saver",
        "type": "address"
      },
      {
        "internalType": "uint32",
        "name": "period",
        "type": "uint32"
      }
    ],
    "name": "HistoryLost",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "tier",
        "type": "uint8"
      },
      {
        "internalType": "uint32",
        "name": "index",
        "type": "uint32"
      }
    ],
    "name": "InvalidPrizeIndex",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "tier",
        "type": "uint8"
      }
    ],
    "name": "InvalidTier",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotASaver",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotTheAsset",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotThePrizePool",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "OwnableInvalidOwner",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "OwnableUnauthorizedAccount",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "period",
        "type": "uint32"
      }
    ],
    "name": "PeriodNotOver",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PeriodTooShort",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PrizePoolAlreadySet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PrizePoolNotSet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ReentrancyGuardReentrantCall",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "RenounceDisabled",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      }
    ],
    "name": "SafeERC20FailedOperation",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "handle",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "sender",
        "type": "address"
      }
    ],
    "name": "SenderNotAllowedToUseHandle",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZamaProtocolUnsupported",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroAddress",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      },
      {
        "indexed": true,
        "internalType": "uint8",
        "name": "tier",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "euint64",
        "name": "carryHandle",
        "type": "bytes32"
      }
    ],
    "name": "CarryPublished",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "saver",
        "type": "address"
      }
    ],
    "name": "Deposited",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "euint64",
        "name": "unfunded",
        "type": "bytes32"
      }
    ],
    "name": "DrawFinalized",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "saver",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "Evaluated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "saver",
        "type": "address"
      }
    ],
    "name": "Withdrawn",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "MAX_BATCH",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "asset",
    "outputs": [
      {
        "internalType": "contract IERC7984",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "tier",
        "type": "uint8"
      }
    ],
    "name": "carryHandle",
    "outputs": [
      {
        "internalType": "euint64",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "saver",
        "type": "address"
      }
    ],
    "name": "confidentialBalanceOf",
    "outputs": [
      {
        "internalType": "euint64",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "saver",
        "type": "address"
      }
    ],
    "name": "confidentialWinningsOf",
    "outputs": [
      {
        "internalType": "euint64",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      },
      {
        "internalType": "address",
        "name": "saver",
        "type": "address"
      }
    ],
    "name": "creditHandle",
    "outputs": [
      {
        "internalType": "euint64",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "currentPeriod",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "cursorOf",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      },
      {
        "internalType": "uint256",
        "name": "count",
        "type": "uint256"
      }
    ],
    "name": "evaluate",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      },
      {
        "internalType": "address",
        "name": "saver",
        "type": "address"
      }
    ],
    "name": "evaluated",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "evaluatedCount",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "finalizeDraw",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "finalized",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "saver",
        "type": "address"
      }
    ],
    "name": "firstObservationAt",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "firstPeriodAt",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "saver",
        "type": "address"
      }
    ],
    "name": "isSaver",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "maxPrincipal",
    "outputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "saver",
        "type": "address"
      },
      {
        "internalType": "uint8",
        "name": "slot",
        "type": "uint8"
      }
    ],
    "name": "observationOf",
    "outputs": [
      {
        "internalType": "euint64",
        "name": "cum",
        "type": "bytes32"
      },
      {
        "internalType": "euint64",
        "name": "balance",
        "type": "bytes32"
      },
      {
        "internalType": "uint32",
        "name": "ts",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "opened",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "paused",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "period",
        "type": "uint32"
      }
    ],
    "name": "periodEnd",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "periodLength",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "periodOf",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "prizePool",
    "outputs": [
      {
        "internalType": "contract IHearthPrizePool",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "tier",
        "type": "uint8"
      }
    ],
    "name": "publishedCarry",
    "outputs": [
      {
        "internalType": "euint64",
        "name": "handle",
        "type": "bytes32"
      },
      {
        "internalType": "uint32",
        "name": "publishedAt",
        "type": "uint32"
      },
      {
        "internalType": "bool",
        "name": "pending",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "remainingHandles",
    "outputs": [
      {
        "internalType": "euint64[3]",
        "name": "",
        "type": "bytes32[3]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      }
    ],
    "name": "saverAt",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "saverCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      },
      {
        "internalType": "address",
        "name": "saver",
        "type": "address"
      },
      {
        "internalType": "uint8",
        "name": "tier",
        "type": "uint8"
      },
      {
        "internalType": "uint32",
        "name": "index",
        "type": "uint32"
      }
    ],
    "name": "thresholdOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "threshold",
        "type": "uint256"
      },
      {
        "internalType": "bool",
        "name": "skipped",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "unfundedHandle",
    "outputs": [
      {
        "internalType": "euint64",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "walkOf",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "start",
        "type": "uint32"
      },
      {
        "internalType": "uint32",
        "name": "count",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      },
      {
        "internalType": "address",
        "name": "saver",
        "type": "address"
      }
    ],
    "name": "weightHandle",
    "outputs": [
      {
        "internalType": "euint64",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "windowEndsAt",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "externalEuint64",
        "name": "encryptedAmount",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "inputProof",
        "type": "bytes"
      }
    ],
    "name": "withdraw",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "withdrawAll",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

export const HEARTH_POOL_ABI = [
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "AlreadyClosed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CannotRescueAsset",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "tier",
        "type": "uint8"
      }
    ],
    "name": "CarryNotPending",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "CloseWindowClosed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EnforcedPause",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ExpectedPause",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidKMSSignatures",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "scaleBits",
        "type": "uint8"
      }
    ],
    "name": "InvalidScaleBits",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "tier",
        "type": "uint8"
      }
    ],
    "name": "InvalidTier",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotTheVault",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NothingToClose",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "OwnableInvalidOwner",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "OwnableUnauthorizedAccount",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ReentrancyGuardReentrantCall",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "RenounceDisabled",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      }
    ],
    "name": "SafeERC20FailedOperation",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      },
      {
        "internalType": "enum IHearthPrizePool.DrawStatus",
        "name": "status",
        "type": "uint8"
      }
    ],
    "name": "WrongStatus",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "YieldSourceHasNoCode",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZamaProtocolUnsupported",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroAddress",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "seed",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint8",
        "name": "scaleBits",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "harvested",
        "type": "uint64"
      }
    ],
    "name": "DrawAwarded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "euint64",
        "name": "seedHandle",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "euint8",
        "name": "scaleHandle",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "ebool",
        "name": "nonEmptyHandle",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "euint64",
        "name": "harvestHandle",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "uint64[3]",
        "name": "prize",
        "type": "uint64[3]"
      },
      {
        "indexed": false,
        "internalType": "uint64[3]",
        "name": "offered",
        "type": "uint64[3]"
      }
    ],
    "name": "DrawClosed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "harvested",
        "type": "uint64"
      }
    ],
    "name": "DrawEmpty",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "harvested",
        "type": "uint64"
      }
    ],
    "name": "DrawSkipped",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "HarvestFailed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      },
      {
        "indexed": true,
        "internalType": "uint8",
        "name": "tier",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "carry",
        "type": "uint64"
      }
    ],
    "name": "TierReconciled",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "UTILISATION_BPS",
    "outputs": [
      {
        "internalType": "uint16",
        "name": "",
        "type": "uint16"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "asset",
    "outputs": [
      {
        "internalType": "contract IERC7984",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      },
      {
        "internalType": "uint64",
        "name": "seed",
        "type": "uint64"
      },
      {
        "internalType": "uint8",
        "name": "scaleCount",
        "type": "uint8"
      },
      {
        "internalType": "bool",
        "name": "nonEmpty",
        "type": "bool"
      },
      {
        "internalType": "uint64",
        "name": "harvested",
        "type": "uint64"
      },
      {
        "internalType": "bytes",
        "name": "proof",
        "type": "bytes"
      }
    ],
    "name": "awardDraw",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "canClose",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "closableDraw",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "closeDeadline",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "closeDraw",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "closeDraw",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "currentPeriod",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "drawOf",
    "outputs": [
      {
        "components": [
          {
            "internalType": "enum IHearthPrizePool.DrawStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "euint64",
            "name": "seedHandle",
            "type": "bytes32"
          },
          {
            "internalType": "euint8",
            "name": "scaleHandle",
            "type": "bytes32"
          },
          {
            "internalType": "ebool",
            "name": "nonEmptyHandle",
            "type": "bytes32"
          },
          {
            "internalType": "euint64",
            "name": "harvestHandle",
            "type": "bytes32"
          },
          {
            "internalType": "uint64",
            "name": "seed",
            "type": "uint64"
          },
          {
            "internalType": "uint8",
            "name": "scaleBits",
            "type": "uint8"
          },
          {
            "internalType": "uint64",
            "name": "harvested",
            "type": "uint64"
          },
          {
            "internalType": "uint64[3]",
            "name": "prize",
            "type": "uint64[3]"
          },
          {
            "internalType": "uint64[3]",
            "name": "offered",
            "type": "uint64[3]"
          }
        ],
        "internalType": "struct HearthPrizePool.Draw",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "drawParams",
    "outputs": [
      {
        "components": [
          {
            "internalType": "enum IHearthPrizePool.DrawStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "uint64[3]",
            "name": "prize",
            "type": "uint64[3]"
          },
          {
            "internalType": "uint64[3]",
            "name": "offered",
            "type": "uint64[3]"
          },
          {
            "internalType": "uint64[3]",
            "name": "zoneMul",
            "type": "uint64[3]"
          },
          {
            "internalType": "uint64[3]",
            "name": "zoneDiv",
            "type": "uint64[3]"
          },
          {
            "internalType": "uint32[3]",
            "name": "prizeCount",
            "type": "uint32[3]"
          },
          {
            "internalType": "uint64",
            "name": "seed",
            "type": "uint64"
          },
          {
            "internalType": "uint8",
            "name": "scaleBits",
            "type": "uint8"
          }
        ],
        "internalType": "struct IHearthPrizePool.DrawParams",
        "name": "params",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "lastClosedDraw",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "liquidity",
    "outputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "paused",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "tier",
        "type": "uint8"
      },
      {
        "internalType": "uint64",
        "name": "carry",
        "type": "uint64"
      },
      {
        "internalType": "bytes",
        "name": "proof",
        "type": "bytes"
      }
    ],
    "name": "reconcile",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "tier",
        "type": "uint8"
      }
    ],
    "name": "reconcileEvery",
    "outputs": [
      {
        "internalType": "uint16",
        "name": "",
        "type": "uint16"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "scaleBits",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "tier",
        "type": "uint8"
      }
    ],
    "name": "tierOf",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint32",
            "name": "prizeCount",
            "type": "uint32"
          },
          {
            "internalType": "uint64",
            "name": "oddsNumerator",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "oddsDenominator",
            "type": "uint64"
          },
          {
            "internalType": "uint16",
            "name": "shares",
            "type": "uint16"
          },
          {
            "internalType": "uint16",
            "name": "reconcileEvery",
            "type": "uint16"
          }
        ],
        "internalType": "struct HearthPrizePool.Tier",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "vault",
    "outputs": [
      {
        "internalType": "contract IHearthVault",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "drawId",
        "type": "uint32"
      }
    ],
    "name": "windowEndsAt",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "yieldSource",
    "outputs": [
      {
        "internalType": "contract IYieldSource",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

export const HEARTH_SOURCE_ABI = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "amount",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "balance",
        "type": "uint64"
      }
    ],
    "name": "Harvested",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "ratePerSecond",
        "type": "uint64"
      }
    ],
    "name": "RateChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "amount",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "balance",
        "type": "uint64"
      }
    ],
    "name": "Sponsored",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "asset",
    "outputs": [
      {
        "internalType": "contract IERC7984ERC20Wrapper",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "balance",
    "outputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "harvestable",
    "outputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "ratePerSecond",
    "outputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "recipient",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "underlying",
    "outputs": [
      {
        "internalType": "contract IERC20",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

export const CONFIDENTIAL_ASSET_ABI = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "euint64",
        "name": "amount",
        "type": "bytes32"
      }
    ],
    "name": "ConfidentialTransfer",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "receiver",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "unwrapRequestId",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "euint64",
        "name": "encryptedAmount",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "cleartextAmount",
        "type": "uint64"
      }
    ],
    "name": "UnwrapFinalized",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "receiver",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "unwrapRequestId",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "euint64",
        "name": "amount",
        "type": "bytes32"
      }
    ],
    "name": "UnwrapRequested",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "confidentialBalanceOf",
    "outputs": [
      {
        "internalType": "euint64",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "confidentialTotalSupply",
    "outputs": [
      {
        "internalType": "euint64",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "euint64",
        "name": "amount",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "confidentialTransferAndCall",
    "outputs": [
      {
        "internalType": "euint64",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "externalEuint64",
        "name": "encryptedAmount",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "inputProof",
        "type": "bytes"
      },
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "confidentialTransferAndCall",
    "outputs": [
      {
        "internalType": "euint64",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "decimals",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "unwrapRequestId",
        "type": "bytes32"
      },
      {
        "internalType": "uint64",
        "name": "unwrapAmountCleartext",
        "type": "uint64"
      },
      {
        "internalType": "bytes",
        "name": "decryptionProof",
        "type": "bytes"
      }
    ],
    "name": "finalizeUnwrap",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "name",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "rate",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "symbol",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "underlying",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "externalEuint64",
        "name": "encryptedAmount",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "inputProof",
        "type": "bytes"
      }
    ],
    "name": "unwrap",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "euint64",
        "name": "amount",
        "type": "bytes32"
      }
    ],
    "name": "unwrap",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "unwrapRequestId",
        "type": "bytes32"
      }
    ],
    "name": "unwrapAmount",
    "outputs": [
      {
        "internalType": "euint64",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "wrap",
    "outputs": [
      {
        "internalType": "euint64",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;
