// Writes src/lib/chain/abis.ts from the compiled Hardhat artifacts, so the app can never drift
// from the contracts it talks to. Only the entries the app actually uses are emitted: a full
// HearthVault ABI as a TypeScript `as const` costs seconds of type inference on every check.
//
// Run: node scripts/generate-abis.mjs   (from packages/web)

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const web = resolve(here, "..");
const artifacts = resolve(web, "..", "contracts", "artifacts", "contracts");
const out = join(web, "src", "lib", "chain", "abis.ts");

const WANTED = {
  HEARTH_VAULT_ABI: {
    file: "HearthVault.sol/HearthVault.json",
    functions: [
      "asset",
      "prizePool",
      "periodLength",
      "firstPeriodAt",
      "maxPrincipal",
      "paused",
      "currentPeriod",
      "periodOf",
      "periodEnd",
      "windowEndsAt",
      "saverCount",
      "saverAt",
      "isSaver",
      "firstObservationAt",
      "confidentialBalanceOf",
      "confidentialWinningsOf",
      "weightHandle",
      "creditHandle",
      "thresholdOf",
      "observationOf",
      "evaluated",
      "evaluatedCount",
      "cursorOf",
      "walkOf",
      "remainingHandles",
      "carryHandle",
      "publishedCarry",
      "finalized",
      "opened",
      "unfundedHandle",
      "MAX_BATCH",
      "withdraw",
      "withdrawAll",
      "evaluate",
      "finalizeDraw",
    ],
    events: ["Deposited", "Withdrawn", "Evaluated", "DrawFinalized", "CarryPublished"],
    errors: true,
  },
  HEARTH_POOL_ABI: {
    file: "HearthPrizePool.sol/HearthPrizePool.json",
    functions: [
      "vault",
      "asset",
      "yieldSource",
      "paused",
      "scaleBits",
      "liquidity",
      "lastClosedDraw",
      "drawOf",
      "drawParams",
      "tierOf",
      "reconcileEvery",
      "canClose",
      "closableDraw",
      "closeDeadline",
      "currentPeriod",
      "windowEndsAt",
      "UTILISATION_BPS",
      "closeDraw",
      "awardDraw",
      "reconcile",
    ],
    events: ["DrawClosed", "DrawAwarded", "DrawEmpty", "DrawSkipped", "TierReconciled", "HarvestFailed"],
    errors: true,
  },
  HEARTH_SOURCE_ABI: {
    file: "SponsoredYieldSource.sol/SponsoredYieldSource.json",
    functions: ["asset", "underlying", "recipient", "ratePerSecond", "balance", "harvestable"],
    events: ["Sponsored", "Harvested", "RateChanged"],
    errors: false,
  },
  // Zama's cUSDCMock is a fork of this OpenZeppelin wrapper. Every entry below is the standard
  // ERC-7984 wrapper surface, which both implement identically; the fork's own additions
  // (observers, pause, deny list) are hand written in TOKEN_GOVERNANCE_ABI because no artifact of
  // that contract exists in this repo.
  CONFIDENTIAL_ASSET_ABI: {
    file: "ConfidentialUSDC.sol/ConfidentialUSDC.json",
    functions: [
      "name",
      "symbol",
      "decimals",
      "rate",
      "underlying",
      "confidentialBalanceOf",
      "confidentialTotalSupply",
      "wrap",
      "confidentialTransferAndCall",
      "unwrap",
      "finalizeUnwrap",
      "unwrapAmount",
    ],
    events: ["ConfidentialTransfer", "UnwrapRequested", "UnwrapFinalized"],
    errors: false,
  },
};

function read(relative) {
  const path = join(artifacts, relative);
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch (error) {
    throw new Error(
      `Could not read ${path}. Run "npm run compile -w @hearth/contracts" first. (${String(error)})`,
    );
  }
}

function pick(abi, spec, name) {
  const kept = abi.filter((entry) => {
    if (entry.type === "function") return spec.functions.includes(entry.name);
    if (entry.type === "event") return spec.events.includes(entry.name);
    if (entry.type === "error") return spec.errors;
    return false;
  });

  const found = new Set(kept.filter((e) => e.type === "function").map((e) => e.name));
  const missingFn = spec.functions.filter((n) => !found.has(n));
  const foundEvents = new Set(kept.filter((e) => e.type === "event").map((e) => e.name));
  const missingEv = spec.events.filter((n) => !foundEvents.has(n));
  if (missingFn.length > 0 || missingEv.length > 0) {
    throw new Error(
      `${name} is missing ${[...missingFn, ...missingEv].join(", ")} in the compiled artifact. ` +
        "The contract changed, so the list in scripts/generate-abis.mjs has to change with it.",
    );
  }
  return kept;
}

const banner = `// Generated by scripts/generate-abis.mjs from packages/contracts/artifacts. Do not edit by hand.
// Regenerate after any contract change: npm run abis -w @hearth/web
`;

const parts = [banner];
for (const [constant, spec] of Object.entries(WANTED)) {
  const abi = read(spec.file).abi;
  const kept = pick(abi, spec, constant);
  parts.push(`export const ${constant} = ${JSON.stringify(kept, null, 2)} as const;\n`);
}

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, parts.join("\n"), "utf8");
console.log(`wrote ${out} with ${Object.keys(WANTED).length} ABIs`);
